version: '2'

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1

    steps:
      - checkout

      - restore_cache:
          key: v1-wait-for-{{ arch }}-{{ checksum "project.clj" }}

      - run:
          name: Install dependencies
          command: lein deps

      - save_cache:
          key: v1-wait-for-{{ arch }}-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - run:
          name: Build Jar
          command: lein jar

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                lein deploy private
            fi
